# Nome da pipeline
name: Minha primeira pipeline

# Quando a pipeline será executada
on:
  push:
    branches:
      - main

# Trabalhos que serão executados
jobs:
  # Nome do trabalho
  executar-java:
    # Sistema operacional utilizado
    runs-on: ubuntu-latest

    # Etapas do trabalho
    steps:
      # Baixa o código do repositório
      - name: Baixar código
        uses: actions/checkout@v5

      # Configura o Java 21
      - name: Configurar Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      # Compila o programa
      - name: Compilar
        run: javac Main.java

      # Executa o programa
      - name: Executar
        run: java Main